# Markdownlint configuration
# Relax some rules for narrative content, keep structure hygiene.
MD013: false        # line length
MD033: false        # inline HTML allowed
MD041: false        # first-line heading not required
MD024: {allow_different_nesting: true}  # duplicate heading allowed in different contexts
MD004: {style: dash}    # list marker style
MD029: true             # ordered list item prefix
MD007: {indent: 2}
MD025: true             # multiple top-level headings check
MD030: true             # spaces after list markers