#!/usr/bin/env python3
"""
Fill all empty folders in the vault with appropriate content
"""

import os
from pathlib import Path
from datetime import datetime
import json

# Define content templates for each folder type
FOLDER_CONTENT = {
    "06_GM_Resources/Session_Tools": [
        ("Session_Planning_Template.md", "# Session Planning Template\n\n---\ntype: Resource\nstatus: active\ntags:\n- gm-tool\n- session-planning\ncreated: 2025-08-13\n---\n\n## Session Overview\n\n### Session Number\n### Date\n### Players Present\n### Session Duration\n\n## Session Goals\n\n### Primary Objective\n- [ ] Main quest advancement\n- [ ] Character development moment\n- [ ] World event introduction\n\n### Secondary Goals\n- [ ] NPC introduction\n- [ ] Foreshadowing\n- [ ] Item discovery\n\n## Scene Planning\n\n### Scene 1: Opening\n**Location**: \n**NPCs**: \n**Objective**: \n**Potential Complications**: \n\n### Scene 2: Development\n**Location**: \n**NPCs**: \n**Objective**: \n**Potential Complications**: \n\n### Scene 3: Climax\n**Location**: \n**NPCs**: \n**Objective**: \n**Potential Complications**: \n\n## NPCs This Session\n\n### Returning NPCs\n- Name: Role, Motivation\n\n### New NPCs\n- Name: Role, Motivation\n\n## Combat Encounters\n\n### Encounter 1\n**CR**: \n**Enemies**: \n**Terrain**: \n**Special Conditions**: \n\n## Loot & Rewards\n\n### Treasure\n- Gold: \n- Items: \n\n### Story Rewards\n- Information: \n- Allies: \n- Reputation: \n\n## Contingency Plans\n\n### If Players Go Off-Track\n- Option 1: \n- Option 2: \n\n### If Session Runs Short\n- Additional encounter: \n- Character moment: \n\n### If Session Runs Long\n- Good stopping point: \n- Cliffhanger option: \n\n## Session Notes\n\n### What Actually Happened\n\n### Player Decisions\n\n### Unexpected Developments\n\n### Follow-Up Required"),
        
        ("Initiative_Tracker.md", "# Initiative Tracker\n\n---\ntype: Tool\nstatus: active\ntags:\n- combat\n- initiative\ncreated: 2025-08-13\n---\n\n## Combat Round: ___\n\n| Initiative | Name | HP Current/Max | AC | Conditions | Actions Taken |\n|------------|------|----------------|----|-----------|--------------|\n| 25 | | / | | | |\n| 24 | | / | | | |\n| 23 | | / | | | |\n| 22 | | / | | | |\n| 21 | | / | | | |\n| 20 | | / | | | |\n| 19 | | / | | | |\n| 18 | | / | | | |\n| 17 | | / | | | |\n| 16 | | / | | | |\n| 15 | | / | | | |\n| 14 | | / | | | |\n| 13 | | / | | | |\n| 12 | | / | | | |\n| 11 | | / | | | |\n| 10 | | / | | | |\n| 9 | | / | | | |\n| 8 | | / | | | |\n| 7 | | / | | | |\n| 6 | | / | | | |\n| 5 | | / | | | |\n| 4 | | / | | | |\n| 3 | | / | | | |\n| 2 | | / | | | |\n| 1 | | / | | | |\n\n## Environmental Effects\n- [ ] Difficult Terrain\n- [ ] Obscured Vision\n- [ ] Pressure Effects (Aquabyssos)\n- [ ] Wind Effects (Aethermoor)\n- [ ] Crystal Corruption\n\n## Lair Actions (Initiative 20)\n\n## Legendary Actions Available\n\n## Concentration Tracking\n| Caster | Spell | DC | Duration Remaining |\n|--------|-------|----|--------------------|"),
        
        ("NPC_Quick_Generator.md", "# NPC Quick Generator\n\n---\ntype: Tool\nstatus: active\ntags:\n- npc\n- generator\ncreated: 2025-08-13\n---\n\n## Quick NPC Stats\n\n### Name Generator\n**Aquabyssos Names**: Marina, Tidal, Coral, Pearl, Depth, Current, Wave, Storm\n**Aethermoor Names**: Sky, Wind, Crystal, Cloud, Star, Zephyr, Aurora, Gale\n\n### Instant Personality (Roll d20)\n1. Nervous and twitchy\n2. Overly friendly\n3. Suspicious of outsiders\n4. Constantly eating\n5. Speaks in whispers\n6. Laughs at inappropriate times\n7. Extremely formal\n8. Tells bad jokes\n9. Constantly complaining\n10. Overly helpful\n11. Mysteriously vague\n12. Brutally honest\n13. Easily distracted\n14. Superstitious\n15. Name-drops constantly\n16. Paranoid about shadows\n17. Obsessed with crystals\n18. Fear of depths/heights\n19. Collect strange objects\n20. Speaks in riddles\n\n### Quick Motivations (Roll d12)\n1. Needs money desperately\n2. Seeking lost family member\n3. Hiding from someone\n4. Wants to join an organization\n5. Seeking revenge\n6. Looking for love\n7. Pursuing forbidden knowledge\n8. Trying to prove innocence\n9. Fulfilling a prophecy\n10. Paying off a debt\n11. Seeking redemption\n12. Protecting a secret\n\n### Instant Stats Block\n**Commoner**: AC 10, HP 4, Speed 30ft, STR 10, DEX 10, CON 10, INT 10, WIS 10, CHA 10\n**Guard**: AC 16, HP 11, Speed 30ft, STR 13, DEX 12, CON 12, INT 10, WIS 11, CHA 10\n**Noble**: AC 15, HP 9, Speed 30ft, STR 11, DEX 12, CON 11, INT 12, WIS 14, CHA 16\n**Priest**: AC 13, HP 27, Speed 25ft, STR 10, DEX 10, CON 12, INT 13, WIS 16, CHA 13\n**Spy**: AC 12, HP 27, Speed 30ft, STR 10, DEX 15, CON 10, INT 12, WIS 14, CHA 16"),
        
        ("Random_Event_Generator.md", "# Random Event Generator\n\n---\ntype: Tool\nstatus: active\ntags:\n- random-events\n- encounters\ncreated: 2025-08-13\n---\n\n## City Events (Roll d20)\n1. Street performer draws crowd\n2. Pickpocket attempt\n3. Guard patrol stops party\n4. Merchant offers special deal\n5. Building fire breaks out\n6. Noble's carriage blocks street\n7. Public execution announced\n8. Festival parade begins\n9. Beggar shares information\n10. Rival adventurers challenge party\n11. Crystal corruption discovered\n12. Shadow operative spotted\n13. Pressure sickness outbreak\n14. Wind storm approaches\n15. Political demonstration\n16. Guild recruitment drive\n17. Missing person posters\n18. Street fight erupts\n19. Religious procession\n20. Mysterious package delivered\n\n## Wilderness Events (Roll d20)\n1. Weather suddenly changes\n2. Tracks of large creature\n3. Abandoned campsite\n4. Merchant caravan\n5. Bridge washed out\n6. Bandits demand toll\n7. Wounded traveler\n8. Strange lights in distance\n9. Ancient ruins discovered\n10. Wild magic surge\n11. Crystal growth blocking path\n12. Pressure anomaly (Aquabyssos)\n13. Wind current shift (Aethermoor)\n14. Lost child found\n15. Hidden cache discovered\n16. Territorial beast\n17. Poisonous plants\n18. Quicksand/unstable ground\n19. Ghost or spirit\n20. Portal to other realm"),
        
        ("Encounter_Difficulty_Calculator.md", "# Encounter Difficulty Calculator\n\n---\ntype: Tool\nstatus: active\ntags:\n- combat\n- balance\ncreated: 2025-08-13\n---\n\n## Quick XP Thresholds\n\n### Per Character\n| Level | Easy | Medium | Hard | Deadly |\n|-------|------|--------|------|--------|\n| 1 | 25 | 50 | 75 | 100 |\n| 2 | 50 | 100 | 150 | 200 |\n| 3 | 75 | 150 | 225 | 400 |\n| 4 | 125 | 250 | 375 | 500 |\n| 5 | 250 | 500 | 750 | 1100 |\n| 6 | 300 | 600 | 900 | 1400 |\n| 7 | 350 | 750 | 1100 | 1700 |\n| 8 | 450 | 900 | 1400 | 2100 |\n| 9 | 550 | 1100 | 1600 | 2400 |\n| 10 | 600 | 1200 | 1900 | 2800 |\n\n## Encounter Multipliers\n| # Enemies | Multiplier |\n|-----------|------------|\n| 1 | x1 |\n| 2 | x1.5 |\n| 3-6 | x2 |\n| 7-10 | x2.5 |\n| 11-14 | x3 |\n| 15+ | x4 |\n\n## Environmental Modifiers\n- **Aquabyssos Depths**: +1 difficulty if not adapted\n- **Aethermoor Heights**: +1 difficulty if not adapted\n- **Crystal Corruption Zone**: +2 difficulty\n- **Shadow Influence**: Disadvantage on Wisdom saves\n- **Extreme Weather**: Disadvantage on ranged attacks\n\n## Quick Encounter Builder\n\n### Party of 4 Level 5 Characters\n- Easy: 1000 XP\n- Medium: 2000 XP\n- Hard: 3000 XP\n- Deadly: 4400 XP"),
        
        ("Session_Pacing_Guide.md", "# Session Pacing Guide\n\n---\ntype: Guide\nstatus: active\ntags:\n- gm-tool\n- pacing\ncreated: 2025-08-13\n---\n\n## 3-Hour Session Structure\n\n### Opening (30 minutes)\n- Recap previous session (5 min)\n- Set scene and goals (10 min)\n- Initial roleplay/exploration (15 min)\n\n### Rising Action (60 minutes)\n- Investigation/exploration (20 min)\n- NPC interactions (20 min)\n- Skill challenges (20 min)\n\n### Climax (60 minutes)\n- Major combat or confrontation (45 min)\n- Immediate aftermath (15 min)\n\n### Resolution (30 minutes)\n- Loot and rewards (10 min)\n- Downtime activities (10 min)\n- Setup for next session (10 min)\n\n## Pacing Techniques\n\n### Speed Things Up\n- Skip to the action\n- Summarize travel\n- Group skill checks\n- Set real-time limits\n\n### Slow Things Down\n- Add sensory details\n- Focus on character moments\n- Explore NPC backstories\n- Environmental storytelling\n\n## Warning Signs\n\n### Too Fast\n- Players confused about events\n- Missing important clues\n- No character development\n- Rushing through content\n\n### Too Slow\n- Players checking phones\n- Analysis paralysis\n- Repetitive discussions\n- No progress on goals"),
        
        ("Loot_Generator.md", "# Loot Generator\n\n---\ntype: Tool\nstatus: active\ntags:\n- treasure\n- loot\ncreated: 2025-08-13\n---\n\n## Individual Treasure (Roll d100)\n\n### CR 0-4\n01-30: 5d6 copper pieces\n31-60: 4d6 silver pieces\n61-70: 3d6 gold pieces\n71-90: 2d6 gold pieces + minor trinket\n91-00: 1d6 platinum pieces + gem (10gp)\n\n### CR 5-10\n01-30: 4d6 x 10 silver pieces\n31-60: 6d6 x 10 gold pieces\n61-70: 3d6 x 10 gold + gem (50gp)\n71-90: 4d6 x 10 gold + art object (250gp)\n91-00: 2d6 x 10 platinum + minor magic item\n\n## Aquabyssos-Specific Treasures\n- Pearl of Power\n- Coral Crown\n- Depth Gauge\n- Pressure Pills\n- Bioluminescent Ink\n- Tidal Chart\n- Memory Pearl\n\n## Aethermoor-Specific Treasures\n- Wind Rose\n- Crystal Focus\n- Altitude Tonic\n- Storm Glass\n- Feather Token\n- Sky Map\n- Cloud Silk\n\n## Minor Magic Items\n1. Potion of Healing\n2. Scroll of Identify\n3. Bag of Tricks\n4. Driftglobe\n5. Immovable Rod\n6. Rope of Climbing"),
        
        ("Condition_Tracker.md", "# Condition Tracker\n\n---\ntype: Reference\nstatus: active\ntags:\n- conditions\n- status-effects\ncreated: 2025-08-13\n---\n\n## Standard Conditions Quick Reference\n\n### Blinded\n- Can't see\n- Auto-fail sight checks\n- Disadvantage on attacks\n- Advantage against them\n\n### Charmed\n- Can't attack charmer\n- Charmer has advantage on social\n\n### Deafened\n- Can't hear\n- Auto-fail hearing checks\n\n### Exhaustion\n1. Disadvantage on ability checks\n2. Speed halved\n3. Disadvantage on attacks and saves\n4. HP maximum halved\n5. Speed reduced to 0\n6. Death\n\n### Frightened\n- Disadvantage while seeing source\n- Can't willingly move closer\n\n### Grappled\n- Speed becomes 0\n- Ends if grappler incapacitated\n\n### Paralyzed\n- Incapacitated, can't move/speak\n- Auto-fail STR/DEX saves\n- Attacks have advantage\n- Hits are crits in 5ft\n\n### Poisoned\n- Disadvantage on attacks and ability checks\n\n### Prone\n- Disadvantage on attacks\n- Melee attacks have advantage\n- Ranged attacks have disadvantage\n\n### Restrained\n- Speed 0\n- Disadvantage on attacks\n- Disadvantage on DEX saves\n- Advantage against them\n\n### Stunned\n- Incapacitated\n- Can't move\n- Can speak only falteringly\n- Auto-fail STR/DEX saves\n- Advantage against them\n\n### Unconscious\n- Incapacitated\n- Can't move or speak\n- Unaware\n- Drop held items, fall prone\n- Auto-fail STR/DEX saves\n- Advantage against them\n- Hits are crits in 5ft\n\n## Campaign-Specific Conditions\n\n### Pressure Sickness (Aquabyssos)\n- Level 1: -5 ft movement\n- Level 2: Disadvantage on CON saves\n- Level 3: 1 exhaustion per hour\n\n### Altitude Sickness (Aethermoor)\n- Level 1: -5 ft movement\n- Level 2: Disadvantage on CON saves\n- Level 3: 1 exhaustion per hour\n\n### Crystal Corruption\n- Stage 1: Cosmetic crystals\n- Stage 2: +2 AC, -10 ft movement\n- Stage 3: Resistance to physical, vulnerability to thunder\n- Stage 4: Loss of self"),
        
        ("World_Event_Calendar.md", "# World Event Calendar\n\n---\ntype: Tool\nstatus: active\ntags:\n- calendar\n- events\ncreated: 2025-08-13\n---\n\n## Recurring Events\n\n### Monthly\n- **New Moon**: Shadow activity increases\n- **Full Moon**: Tidal extremes in Aquabyssos\n- **Crystal Resonance**: Cross-realm communication easiest\n- **Market Day**: Major trading\n\n### Seasonal\n\n#### Spring\n- Festival of Currents (Aquabyssos)\n- Wind Dance Festival (Aethermoor)\n- Planting ceremonies\n- Guild recruitments\n\n#### Summer\n- Depth Trials (Aquabyssos)\n- Sky Races (Aethermoor)\n- Trade summit\n- Military exercises\n\n#### Fall\n- Harvest celebrations\n- Ancestor remembrance\n- Parliament sessions\n- Academy examinations\n\n#### Winter\n- Crystal Festival\n- Deep Mother vigil\n- Storm season\n- Diplomatic season\n\n## Random Events (Roll d20 weekly)\n\n1-5: Nothing significant\n6-8: Minor local event\n9-11: Regional development\n12-14: Political change\n15-16: Natural phenomenon\n17-18: Military movement\n19: Planar disturbance\n20: Major world event\n\n## Current Year Events\n\n### Scheduled\n- Month 3: Parliamentary elections\n- Month 6: Trade route renegotiation\n- Month 9: Crystal harvest\n- Month 12: Succession ceremony\n\n### Developing Situations\n- Shadow Conspiracy investigation\n- Crystal plague spreading\n- Deep Mother stirring\n- Cross-realm tensions"),
        
        ("GM_Screen_Reference.md", "# GM Screen Quick Reference\n\n---\ntype: Reference\nstatus: active\ntags:\n- gm-screen\n- quick-reference\ncreated: 2025-08-13\n---\n\n## DCs by Difficulty\n- Very Easy: 5\n- Easy: 10\n- Medium: 15\n- Hard: 20\n- Very Hard: 25\n- Nearly Impossible: 30\n\n## Advantage/Disadvantage\n- Roll twice, take higher/lower\n- Don't stack\n- Cancel each other out\n\n## Actions in Combat\n- Attack\n- Cast a Spell\n- Dash (double movement)\n- Disengage (no opportunity attacks)\n- Dodge (disadvantage against you)\n- Help (give advantage)\n- Hide (Stealth check)\n- Ready (trigger action)\n- Search (Perception/Investigation)\n- Use an Object\n\n## Bonus Actions\n- Only if granted by ability\n- Once per turn\n\n## Reactions\n- Once per round\n- Opportunity attacks\n- Readied actions\n- Specific abilities\n\n## Movement\n- Can split movement\n- Difficult terrain costs double\n- Prone: half speed to stand\n\n## Cover\n- Half: +2 AC and DEX saves\n- 3/4: +5 AC and DEX saves\n- Total: Can't be targeted directly\n\n## Light\n- Bright: Normal vision\n- Dim: Lightly obscured, disadvantage on Perception\n- Darkness: Heavily obscured, effectively blinded\n\n## Travel Pace\n| Pace | Per Hour | Per Day | Effect |\n|------|----------|---------|--------|\n| Slow | 2 miles | 18 miles | Can stealth |\n| Normal | 3 miles | 24 miles | - |\n| Fast | 4 miles | 30 miles | -5 to passive Perception |")
    ],
    
    "06_GM_Resources/Reference_Cards": [
        ("Combat_Quick_Reference.md", "# Combat Quick Reference Card\n\n---\ntype: Reference\nstatus: active\ntags:\n- combat\n- reference\ncreated: 2025-08-13\n---\n\n## Turn Order\n1. Determine surprise\n2. Roll initiative\n3. Take turns in order\n4. Begin next round\n\n## On Your Turn\n- Movement (can split)\n- Action\n- Bonus Action (if available)\n- Free interactions\n\n## Attack Roll\n1d20 + ability modifier + proficiency (if proficient)\n\n## Damage Roll\nWeapon/spell dice + ability modifier\n\n## Critical Hits\n- Natural 20 on attack\n- Roll damage dice twice\n\n## Death Saves\n- At 0 HP, unconscious\n- DC 10 CON save each turn\n- 3 successes = stable\n- 3 failures = death\n- Natural 1 = 2 failures\n- Natural 20 = 1 HP\n\n## Healing\n- Any healing from 0 HP = conscious\n- Reset death saves\n\n## Opportunity Attacks\n- Enemy leaves reach\n- Use reaction\n- One attack only"),
    ],
    
    "07_Player_Resources/Character_Options": [
        ("Depth_Walker_Ranger.md", "# Depth Walker Ranger\n\n---\ntype: Character Build\nstatus: active\ntags:\n- character-options\n- ranger\n- aquabyssos\ncreated: 2025-08-13\n---\n\n## Character Concept\nDepth Walkers are specialized rangers who navigate the crushing depths of Aquabyssos, serving as guides, scouts, and protectors in the underwater realm.\n\n## Build Overview\n**Race**: Triton or Sea Elf\n**Class**: Ranger\n**Subclass**: Gloom Stalker (reflavored for depths)\n**Background**: Outlander or Marine\n\n## Ability Scores (Priority)\n1. Wisdom (perception in murky depths)\n2. Dexterity (swimming agility)\n3. Constitution (pressure resistance)\n\n## Key Features\n\n### Level 1-4\n- **Favored Enemy**: Aberrations (Deep Mother's spawn)\n- **Natural Explorer**: Underwater\n- **Fighting Style**: Archery (harpoons)\n\n### Level 5-8\n- **Extra Attack**\n- **Depth Sense**: Darkvision 90ft\n- **Pressure Adaptation**: Resistance to pressure\n\n### Level 9-12\n- **Improved Invisibility**: Blend with depths\n- **Stalker's Flurry**: Extra attacks\n\n## Equipment\n- Pressure suit (studded leather)\n- Harpoon launcher (heavy crossbow)\n- Bioluminescent markers\n- Depth gauge\n- Emergency ascent pills\n\n## Roleplay Notes\n- Speak in nautical terms\n- Always checking depth/pressure\n- Suspicious of surface dwellers\n- Protective of ocean secrets"),
    ],
    
    "07_Player_Resources/Handouts": [
        ("Welcome_to_Cordelia.md", "# Welcome to the World of Cordelia\n\n---\ntype: Handout\nstatus: active\ntags:\n- player-handout\n- introduction\ncreated: 2025-08-13\n---\n\n## The Dual Realms\n\nWelcome, adventurer, to Cordelia - a world divided between the crushing depths of Aquabyssos and the soaring heights of Aethermoor.\n\n### Aquabyssos - The Ocean Kingdom\n- Capital: Port Meridian\n- Government: Parliament of Echoes\n- Threats: Pressure madness, Deep Mother cultists, shadow conspiracy\n- Magic: Tidal sorcery, bioluminescence, pressure manipulation\n\n### Aethermoor - The Sky Realm\n- Capital: Crystal Spire\n- Government: The Crystal Throne\n- Threats: Crystal plague, wind storms, reality distortion\n- Magic: Wind weaving, crystal resonance, storm calling\n\n## Current Crisis\n\nThe Convergence Point between realms is expanding. Realities are merging. You must work together - sky and sea - or both worlds will fall.\n\n## Your Role\n\nYou are one of the few who can survive in both realms. Your choices will determine the fate of two civilizations.\n\n## Important Factions\n- The Shadow Conspiracy (hidden threat)\n- Crystal Wardens (Aethermoor protectors)\n- Parliament of Echoes (Aquabyssos government)\n- The Deep Mother Cult (cosmic horror)\n\n## Remember\n- Pressure kills in Aquabyssos without protection\n- Altitude sickness strikes in Aethermoor\n- Crystal corruption changes you permanently\n- Trust no one completely - shadows are everywhere"),
    ],
    
    "03_Mechanics/Transformations": [
        ("Pressure_Adaptation.md", "# Pressure Adaptation Transformation\n\n---\ntype: Mechanic\nstatus: active\ntags:\n- transformation\n- aquabyssos\n- pressure\ncreated: 2025-08-13\n---\n\n## Overview\nPressure Adaptation is the gradual physical transformation that allows surface dwellers to survive in Aquabyssos's crushing depths.\n\n## Transformation Stages\n\n### Stage 1: Initial Adaptation (Days 1-7)\n**Physical Changes**:\n- Slight webbing between fingers\n- Eyes become larger, more light-sensitive\n- Skin develops faint scales\n\n**Mechanical Benefits**:\n- Swimming speed 20 ft\n- Darkvision 30 ft\n- Can hold breath for CON modifier x 2 minutes\n\n**Drawbacks**:\n- Disadvantage on Persuasion with surface dwellers\n- Sunlight sensitivity (disadvantage in bright light)\n\n### Stage 2: Deep Adaptation (Days 8-30)\n**Physical Changes**:\n- Full webbing on hands and feet\n- Gills form on neck\n- Bioluminescent patches appear\n\n**Mechanical Benefits**:\n- Swimming speed 30 ft\n- Breathe underwater\n- Darkvision 60 ft\n- Emit dim light 5 ft radius\n\n**Drawbacks**:\n- Must immerse in water daily or gain exhaustion\n- -10 ft walking speed on land\n- Vulnerability to fire damage\n\n### Stage 3: Complete Transformation (Days 31+)\n**Physical Changes**:\n- Fully aquatic appearance\n- Pressure organ develops\n- Echolocation capability\n\n**Mechanical Benefits**:\n- Swimming speed 40 ft\n- Immunity to pressure\n- Blindsight 30 ft underwater\n- Resistance to cold damage\n\n**Drawbacks**:\n- Cannot survive on land without apparatus\n- Appearance causes fear in surface dwellers\n- Lose ability to use non-aquatic equipment\n\n## Reversal\n- Requires Greater Restoration or Wish\n- Painful process taking 2d6 days\n- 25% chance of permanent changes"),
    ],
    
    "03_Mechanics/Random_Encounters": [
        ("Aquabyssos_Depth_Encounters.md", "# Aquabyssos Depth Encounters\n\n---\ntype: Table\nstatus: active\ntags:\n- encounters\n- aquabyssos\n- random\ncreated: 2025-08-13\n---\n\n## Shallow Depths (0-100 ft)\n\n| d20 | Encounter |\n|-----|----------|\n| 1-2 | Merchant submarine passing |\n| 3-4 | School of bioluminescent fish |\n| 5-6 | Coral harvesters at work |\n| 7-8 | Patrol of city guards |\n| 9-10 | Lost tourist asking directions |\n| 11-12 | Smugglers hiding cargo |\n| 13-14 | Street performer with trained eels |\n| 15-16 | Religious procession |\n| 17-18 | Pressure sickness victim |\n| 19 | Shadow operative watching |\n| 20 | Crystal growth outbreak |\n\n## Medium Depths (100-500 ft)\n\n| d20 | Encounter |\n|-----|----------|\n| 1-2 | Predatory fish pack (sharks) |\n| 3-4 | Underwater ruins |\n| 5-6 | Deep merchant caravan |\n| 7-8 | Kelp forest maze |\n| 9-10 | Thermal vent field |\n| 11-12 | Abandoned research station |\n| 13-14 | Giant octopus lair |\n| 15-16 | Depth cultists ritual |\n| 17-18 | Pressure anomaly |\n| 19 | Memory pearl cache |\n| 20 | Deep Mother vision |\n\n## Crushing Depths (500+ ft)\n\n| d20 | Encounter |\n|-----|----------|\n| 1-2 | Abyssal horror |\n| 3-4 | Ancient mer-folk ruins |\n| 5-6 | Void breach |\n| 7-8 | Pressure-mad explorers |\n| 9-10 | Bioluminescent garden |\n| 11-12 | Depth wurm hunting |\n| 13-14 | Forgotten temple |\n| 15-16 | Reality distortion zone |\n| 17-18 | Elder thing sleeping |\n| 19 | Seven Shards clue |\n| 20 | Deep Mother manifestation |"),
    ],
}

def create_folder_content(vault_path):
    """Create content for all empty folders"""
    created_files = []
    
    for folder_path, files in FOLDER_CONTENT.items():
        full_folder_path = Path(vault_path) / folder_path
        
        # Create folder if it doesn't exist
        full_folder_path.mkdir(parents=True, exist_ok=True)
        
        # Create each file
        for filename, content in files:
            file_path = full_folder_path / filename
            
            # Only create if doesn't exist
            if not file_path.exists():
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(content)
                created_files.append(str(file_path))
                print(f"✅ Created: {file_path.name}")
    
    return created_files

def main():
    """Main execution"""
    vault_path = "/Users/jongosussmango/Library/Mobile Documents/iCloud~md~obsidian/Documents/ObsidianTTRPGVault Experimental"
    
    print("📚 Filling empty folders with appropriate content...")
    print("-" * 50)
    
    created = create_folder_content(vault_path)
    
    print("-" * 50)
    print(f"✅ Created {len(created)} files")
    print("\nFolders populated:")
    for folder in FOLDER_CONTENT.keys():
        print(f"  - {folder}")

if __name__ == "__main__":
    main()